# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black pylint pytest bandit mypy poetry
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with black & pylint
      run: |
        pylint --max-line-length=100 bytechomp
        black --verbose --check --diff --line-length=100 bytechomp
    - name: Type check with Mypy
      run: |
        mypy bytechomp
    - name: Security check with Bandit
      run: |
        bandit -r bytechomp
    - name: Build with Poetry
      run: |
        poetry build --format=wheel
#     - name: Test with pytest
#       run: |
#         pytest
